using System.Collections.Generic;

// NOTE: This file is automatically generated by the GenerateAST tool
public abstract class Expr
{
	public interface Visitor<T>
	{
		T VisitGroupingExpr(Grouping expr);
		T VisitBinaryExpr(Binary expr);
		T VisitUnaryExpr(Unary expr);
		T VisitLogicalExpr(Logical expr);
		T VisitLiteralExpr(Literal expr);
		T VisitVariableExpr(Variable expr);
		T VisitAssignExpr(Assign expr);
	}

	public class Grouping : Expr
	{
		public Grouping(Expr expression)
		{
			this.Expression = expression;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitGroupingExpr(this);
		}

		public Expr Expression;
	}

	public class Binary : Expr
	{
		public Binary(Expr left, Token operation, Expr right)
		{
			this.Left = left;
			this.Operation = operation;
			this.Right = right;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitBinaryExpr(this);
		}

		public Expr Left;
		public Token Operation;
		public Expr Right;
	}

	public class Unary : Expr
	{
		public Unary(Token operation, Expr right)
		{
			this.Operation = operation;
			this.Right = right;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitUnaryExpr(this);
		}

		public Token Operation;
		public Expr Right;
	}

	public class Logical : Expr
	{
		public Logical(Expr left, Token operation, Expr right)
		{
			this.Left = left;
			this.Operation = operation;
			this.Right = right;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitLogicalExpr(this);
		}

		public Expr Left;
		public Token Operation;
		public Expr Right;
	}

	public class Literal : Expr
	{
		public Literal(object value)
		{
			this.Value = value;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitLiteralExpr(this);
		}

		public object Value;
	}

	public class Variable : Expr
	{
		public Variable(Token name)
		{
			this.Name = name;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitVariableExpr(this);
		}

		public Token Name;
	}

	public class Assign : Expr
	{
		public Assign(Token name, Expr value)
		{
			this.name = name;
			this.value = value;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitAssignExpr(this);
		}

		public Token name;
		public Expr value;
	}

	public abstract T Accept<T>(Visitor<T> visitor);
}
