using System.Collections.Generic;

// NOTE: This file is automatically generated by the GenerateAST tool
public abstract class Stmt
{
	public interface Visitor<T>
	{
		T VisitExpressionStmt(Expression stmt);
		T VisitPrintStmt(Print stmt);
	}

	public class Expression : Stmt
	{
		public Expression(Expr expr)
		{
			this.Expr = expr;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitExpressionStmt(this);
		}

		public Expr Expr;
	}

	public class Print : Stmt
	{
		public Print(Expr expr)
		{
			this.Expr = expr;
		}

		public override T Accept<T>(Visitor<T> visitor)
		{
			return visitor.VisitPrintStmt(this);
		}

		public Expr Expr;
	}

	public abstract T Accept<T>(Visitor<T> visitor);
}
